version: "3.8"

services:
  # --- MICROSERVICIO REAL DE INTEGRACIÓN (MODO TEST QA) ---
  app:
    build:
      context: ../                          
      dockerfile: infrastructure/Dockerfile  
      target: final
    ports:
      - "8000-8005:8000"
    volumes:
      - ../:/code                           
    env_file:
      - .env.test
    environment:
      - ENVIRONMENT=qa
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - minio
      - redis

  # --- EMULADOR DE AWS S3 (MINIO) ---
  minio:
    image: minio/minio:latest
    container_name: minio-s3-local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # --- COLA CENTRALIZADA (REDIS) ---
  redis:
    image: redis:7-alpine
    container_name: redis-queue-local
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  minio_data:
  redis_data: