version: "3.8"

services:
  # --- BALANCEADOR DE CARGA / LOAD BALANCER (NGINX) ---
  loadbalancer:
    image: nginx:alpine
    container_name: nginx-lb-local
    ports:
      - "8000:80" # Expone el puerto 8000 hacia tu script de pruebas
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  # --- MICROSERVICIO REAL DE INTEGRACIÓN (REPLICABLE) ---
  app:
    build:
      context: ../                          
      dockerfile: infrastructure/Dockerfile  
      target: final
    # 🚨 NOTA: Se remueve "ports: 8000:8000" para permitir múltiples instancias en paralelo
    volumes:
      - ../:/code                           
    env_file:
      - .env.test
    environment:
      - ENVIRONMENT=qa
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - minio
      - redis

  # --- EMULADOR DE AWS S3 (MINIO) ---
  minio:
    image: minio/minio:latest
    container_name: minio-s3-local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # --- COLA CENTRALIZADA (REDIS) ---
  redis:
    image: redis:7-alpine
    container_name: redis-queue-local
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  minio_data:
  redis_data: