events {
    worker_connections 1024;
}

http {
    # Definimos el grupo de instancias. Docker resolverá 'app:8000' a todas las réplicas
    upstream fastapi_cluster {
        least_conn; # Envía la petición a la instancia con menos conexiones activas
        server app:8000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://fastapi_cluster;
            
            # Encabezados HTTP para preservar la identidad del cliente y trazabilidad
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # ⏱️ Ajuste de Timeouts del Balanceador
            # Evita que Nginx tumbe la conexión si la SFC en QA tarda en responder
            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}